### ISSUE TITLE
Broader CORS recommendations

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/oauth-v2-1#133]
In a [recent commit](5f4d28a5b702346389f1f4bb3cc6044c15031981), I added a paragraph recommending supporting CORS on the token endpoint specifically, if expecting to be used by JS apps.

A [recent discussion](https://bitbucket.org/openid/connect/issues/980/where-else-do-we-need-to-specify-the-use) in OpenID Connect also noted that it would be helpful to point out which endpoints might need to support CORS. 

We should do something similar here, to point out endpoints in the core OAuth spec, and in known extensions, that might need CORS headers if used by SPAs. Additionally, it should be noted where it is _dangerous_ to add CORS support, such as the authorization endpoint.

**Comment by adeinega** [comment]
This's a good discussion, what's interesting is it has been open for a quite while (since 2015).

I guess you referred to 5f4d28a5b702346389f1f4bb3cc6044c15031981 as one of the recent commits on this matter.

**Comment by adeinega** [comment]
The specification may recommend setting CORS policies per client_id + redirect_uri for the authorization endpoint when it's needed for JS clients. The main idea is not to just enable them globally for all the clients.

This should be possible to do because an AS knows what the client_id is (it's one of the parameters in the authorization request). It gets way trickier when it comes to other endpoints (such as the introspect or revocation endpoints), because of "preflight" requests, but I don't think it's completely impossible to do.

**Comment by aaronpk** [comment]
At the very least, it seems the recommendations should be:

* MUST NOT allow CORS requests at the authorization endpoint
* To support JS apps, MUST support CORS requests at the token endpoint
* Any other endpoints defined in extensions that the JS apps may need to call must also support CORS requests, such as AS metadata, revocation, JWK URLs, dynamic client registration, etc.

**Comment by aaronpk** [comment]
Need to sync this with the discussion that's happening with the Security BCP now.

**Comment by aaronpk** [comment]
Security BCP added CORS language here: https://github.com/oauthstuff/draft-ietf-oauth-security-topics/pull/78/files

Ensure this text is in 2.1 but 2.1 can be more descriptive about it as well.

**Comment by aaronpk** [comment]
This was added in 7b398f740ac44626d19836f51a3b087e5d278c9b
